name: ffrd-grid-concept
channels:
  - conda-forge
  - defaults
dependencies:
  - dask
  - rioxarray
  - jupyterlab
  - xarray
  - statsmodels
  - matplotlib
  - zarr
  - h5py
  - geopandas
  - tqdm
  - libgdal-arrow-parquet
